### ISSUE TITLE
Design / Product: Creating Sourcegraph's design principles

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/about#2593]
We're doing some work to define Sourcegraph's design / product principles, which makes for a great story and resource for other teams who want to create principles.

- Motivation
- Process
- Workshop
- Outcomes

I've written a [similar article](https://uxdesign.cc/stop-relying-on-gut-decisions-and-define-your-principles-4761b43d9a09) in the past, but this could be more specific for Sourcegraph and more about the process / how to do it yourself.

We're still in the process of defining our principles, so I think this would be a few weeks away.

**Comment by content-hacker** [comment]
@quinnkeast I moved this post into the assigned column since it looks like you will be writing this - is that correct? If yes, we should remove the `open proposal` label as well. 

My biggest question regarding this pitch is if there if we can find an angle that is appealing to developers. I think diving into the process/approach for how product design principles are created is interesting and can we go a level deeper and talk about how these principles are made with the end-user in mind? We don't want the post to be too specific to Sourcegraph but I think adapting what you've done in the past to appeal to Sourcegraph's audience would be a great iteration. 

In terms of timing, do you have a deadline for when you expect to be finished with this project, and are you drafting as you work on this, or do you plan to write this up at the end? It would be great if we can get a tentative publish date on the calendar and create a work back schedule, even if we are thinking this won't be ready to publish until April.

**Comment by quinnkeast** [comment]
Yes, I plan to write this!

As far as making this appealing for a developer audience, I think there's a few angles:

- Product design principles aren't only for designers: they're for anyone working on a product. That means developers will benefit from having principles themselves, and with luck, they'll be inspired to see if their own company has principles, or if they can spark it themselves!
- An inside look at collaboration between design, product, and engineering at Sourcegraph.
- The actual principles, particularly for those interested in using or working at Sourcegraph!

As to timing:

- The principles are drafted and close to published in our handbook as of today.
- I can have a draft of the article within ~2 weeks for us to carry forward.

Let me know what makes sense to you for a publish target.

**Comment by content-hacker** [comment]
@quinnkeast I like the inside look at the collaboration between design, product, and engineering, using Sourcegraph as an example. I think it would really interesting to detail the process at which you arrived at the final set of principles and offer some constructive takeaways for other teams to use when going through the process themselves. This hits all three of your bullet points. 

In terms of timing, I'd like to set a publishing target for the week of April 5. Does that work for you?
