### ISSUE TITLE
Handbook Page: Routing Internal Questions Not found

### ISSUE THREAD

**Issue by amenne** [sourcegraph/about#2809]
https://about.sourcegraph.com/handbook/ce/routing_questions is returning a page not found error. 

Reference page not associated with a branch which I'm unable to modify: https://github.com/sourcegraph/about/blob/2ec94d00aafbb41eaf6ccf22f783e908f146dc66/handbook/ce/routing_questions.md

**Comment by sqs** [comment]
looking into this now

**Comment by sqs** [comment]
That routing_questions page was removed because it was outdated.

Usually, the handbook will check for links to nonexistent pages, but in this case the link was an absolute URL (`https://about.sourcegraph.com/ce/routing_questions`) instead of a relative link (`routing_questions.md`), and only the latter is checked.

Do you want to revive that page? If so, see https://github.com/sourcegraph/about/pull/2810.

**Comment by amenne** [comment]
Closing; redirected broken link to alternate page.
