### ISSUE TITLE
Look into character that doesn't display in Cloud page

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/about#5058]
Please review the [Slack thread](https://sourcegraph.slack.com/archives/C02E07JDBD3/p1640142009083500). Some people see the "missing" character (photo attached), others don't see anything at all. 

Let's fully remove it.

**Comment by marybelzer** [comment]
Asana card: https://app.asana.com/0/1200095757619647/1201598820385906/f

**Comment by mgyorffy** [comment]
@marybelzer 
- Test results: I tested it on the same version of Google Chrome, Safari, Firefox on desktop, and on iPhone 8 in Safari and was unable to reproduce the issue.
- Research: based on my research this issue is not related to code.
It is actually specific to the device that the user uses.
iOS and Android devices show a different character when an emoji is not available on that device.
iOS shows that square or rectangle with an X in it.
However there's no emoji on this part of the page at all, so there's nothing to remove.
There was an unnecessary empty space there, so I removed that.

So the  official  response  is that  I'm  Unable  to reproduce this issue.
