### ISSUE TITLE
Convert "Request demo" CTA buttons to /demo

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5265]
The Demand Gen team wants to change the "Request demo" CTA buttons on the pages below to point to the /demo page for consistency.

Update the CTA's on the pages below to /demo:

1. https://about.sourcegraph.com/case-studies (bottom CTA)
2. https://about.sourcegraph.com/use-cases (just below hero + in each individual use case section + bottom CTA)
3.  https://about.sourcegraph.com/use-cases/vulnerabilities
4.  https://about.sourcegraph.com/use-cases/code-health
5.  https://about.sourcegraph.com/use-cases/incident-response
6.  https://about.sourcegraph.com/use-cases/onboarding
7.  https://about.sourcegraph.com/use-cases/code-reuse
8. global: Request a Demo CTA in the top nav

This CTA is on hold:

9. https://about.sourcegraph.com/batch-changes (hero section)

These will not be updated:

10. https://about.sourcegraph.com/code-insights (hero section)
11. https://about.sourcegraph.com/pricing/ (all the "contact us" buttons - in Enterprise, Team sections)

Asana: https://app.asana.com/0/1200095757619647/1202133476574746/f

**Comment by zlonko** [comment]
For each page to be tracked, will each also need its own `formId`?

**Comment by zlonko** [comment]
@elzannewentzel For each page to be tracked, will each also need its own `formId`?

**Comment by elzannewentzel** [comment]
@zlonko Looks like we might need to get new embeds for these forms. I'm going to add you to a call with Greg and Erica tomorrow so that we can discuss this more.

**Comment by zlonko** [comment]
@elzannewentzel Revisiting this since we adjusted the scope. Good news, it looks like all of the CTA buttons indicated are already pointing to `/demo`! 

Just to make sure I am up to speed with the new description for this issue: 
- Are we converting any of these CTAs to ChiliPiper forms at this time, or will they just remain buttons? 
- Are we looking to add any other tracking data to them?

--

Here is a breakdown of what I found:

1. `case-studies`: The bottom CTA is within the `TrySourcegraph.tsx` component and points to `/demo`
2. `use-cases`: Each "Request a demo" CTA points to `/demo`. The bottom CTA is within `TrySourcegraph.tsx`
3. `use-cases/vulnerabilities`: All CTAs point to `/demo`
4. `use-cases/code-health`: In development, all CTAs point to `/demo`
5. `use-cases/incident-response`: All CTAs point to `/demo`
6. `use-cases/onboarding`: All CTAs point to `/demo`
7. `use-cases/code-reuse`: In development, all CTAs point to `/demo` 
8. `header.tsx`: "Request a demo" CTA points to `/demo` in the navbar 

The only ones that do not point to `/demo` are:

9. `/batch-changes`: Points to `/contact/request-batch-changes-demo`. Greg said to pause on this one.
10. `/code-insights`: We will not update because ChiliPiper is enabled
11. `/pricing`: Pricing CTAs will be treated differently.

**Comment by zlonko** [comment]
Documenting our exchange in Slack:

> _Tim:_ In addition to pointing these CTAs to /demo, are we converting any of them into ChiliPiper forms? Or will they remain buttons?
> _Greg:_ Since /demo is a Chili Piper form, we can go with the current plan of swapping the CTAs. There needs to be a number of processes built out prior to updating all of the demo requests to one "master" Chili Piper form. The website stripping UTM parameters is also a blocker, so we're paused on that

Considering that all of the CTAs already point to `/demo`, it doesn't seem like there is anything to change at this time. I believe we can resolve the issue.

@bretthayes Would you please give this a look when you have the time? Just checking that I am not missing anything here.

**Comment by bretthayes** [comment]
Looks good to me, thanks @zlonko! I think you've covered everything and the issue with UTM parameters not being preserved through navigation will be fixed in the replatform. It's being tracked in sourcegraph/about-replatform#125 so we can go ahead and close this.
