### ISSUE TITLE
IAM + Admin Experience blog ideas

### ISSUE THREAD

**Issue by nickmyyz** [sourcegraph/about#5352]
Leave ideas here! Include working title, working summary, potential author, and link to draft in progress (if available), or anything else of interest.

**Comment by kopancek** [comment]
One topic that came straight to my mind:
# Why we decided not to go live with Sourcegraph Cloud
**Summary**: We were planning on releasing Sourcegraph Cloud to open beta - meaning any customer would be able to self serve creating their own organization on Cloud. We have decided to not launch the project this year, because it did not align with the customer size that Sourcegraph is targeting this year. It might be interesting to talk about the decision process and why it's OK to change & adapt if we realize need to go in a different direction.
**Potential author**: ideally someone from the triad would be able to help here (@quinnkeast or @ryphil)

**Comment by nickmyyz** [comment]
> 

I think this is a really compelling idea but it might be a heavy lift. We'd want to work with product marketing and run it by the AEs of our remaining Cloud accounts, I imagine. I can ask product marketing if this is a story we want to / feel ready to tell now. They might say yes but at a later date. I'll update you!

**Comment by nickmyyz** [comment]
> Why we decided not to go live with Sourcegraph Cloud

I think this is a really compelling idea but it might be a heavy lift. We'd want to work with product marketing and run it by the AEs of our remaining Cloud accounts, I imagine. I can ask product marketing if this is a story we want to / feel ready to tell now. They might say yes but at a later date. I'll update you!

**Comment by nickmyyz** [comment]
> > Why we decided not to go live with Sourcegraph Cloud
> 
> I think this is a really compelling idea but it might be a heavy lift. We'd want to work with product marketing and run it by the AEs of our remaining Cloud accounts, I imagine. I can ask product marketing if this is a story we want to / feel ready to tell now. They might say yes but at a later date. I'll update you!

@kopancek Update: I talked with Product Marketing and they're interested in doing this post once we settle on a direction for the future of Sourcegraph Cloud. Their thinking is it will serve us better to talk about a new direction as much as the pivot but that having a new direction will also make for a more interesting post. Thank you for surfacing this! Excited to have it on our roadmap, even if it's not immediate.
