### ISSUE TITLE
Clean up interfaces

### ISSUE THREAD

**Issue by zlonko** [sourcegraph/about#5383]
Standardize our interfaces with the same naming convention and file structure. Please see [this comment](https://github.com/sourcegraph/about/pull/5365#discussion_r886157444) for reference.

**Comment by bretthayes** [comment]
Here's what I'm thinking to clean up and standardize our interfaces with file organization and naming conventions:

## Rules of thumb/style guide:
1. If one or more interfaces are needed for a specific component or page, scope and keep them within the component or page
2. If one or more interfaces are needed for many components or pages within the same directory, collocate a file and export the interfaces to import them in the necessary components or pages
3. If one or more interfaces are needed in many pages or components across the codebase, add them to our common/shared interfaces directory and export them

### Example of a scoped interface inside a component

In this case, keep scoped interfaces within the component. Note how it's possible to keep the same namespace since they are thrown away at runtime. Open to standardizing the naming convention to always be `{Name}Props` for convenient search and batch changes.

`components/Button.tsx`
```jsx
import { FunctionComponent } from 'react'

interface Button {
    text: string
}

export const Button: FunctionComponent<Button> = ({ text }) => (
    <button type="button">
        {text}
    </button>
)
```


### Example of an interface inside a component that's been imported

In this case, if the interface is used within the same directory for many sibling/colocated components/pages, add them to a collocated file.

`components/Button/buttonProps.ts`
```ts
export interface ButtonProps {
    text: string
}
```

`components/Button/index.tsx`
```jsx
import { FunctionComponent } from 'react'

import { ButtonProps } from './buttonProps'

export const Button: FunctionComponent<ButtonProps> = ({ text }) => (
    <button type="button">
        {text}
    </button>
)
```

### Example of an interface inside a component that's been imported from our common/shared interfaces directory

In this case, if the interface is used within many components/pages across the codebase, add them to our common/shared interfaces directory to be imported in the necessary components/pages.

`interfaces/index.ts`
```ts
export * from './buttonProps'
```

`interfaces/buttonProps.ts`
```ts
export interface ButtonProps {
    text: string
}
```

`component/Button.tsx`
```jsx
import { FunctionComponent } from 'react'

import { ButtonProps } from '@interfaces'

export const Button: FunctionComponent<ButtonProps> = ({ text }) => (
    <button type="button">
        {text}
    </button>
)
```

**Comment by zlonko** [comment]
Thank you, Brett. This provides a lot of clarity as we scale the About site. My only thought at this time is that I prefer the maintenance advantages of a single naming convention. To me this seems more straightforward in the long-term, especially if we want to change this convention down the road. I am open to what others think as well!

**Comment by st0nebraker** [comment]
I like this! I think it makes sense. Collocate as much as possible, up-leveling the interface only where necessary. Once it's implemented, we can document the structure in our `README` for history, for any new developers stepping in the project, etc.

![image](https://user-images.githubusercontent.com/59381432/172957636-8cb02089-7418-4a1f-9c9a-92977f2bb725.png)

**Comment by zlonko** [comment]
@bretthayes & @st0nebraker Checking for clarity: Shall we stick with two naming conventions or one?

**Comment by bretthayes** [comment]
@zlonko I'm leaning more towards one for much more robust search and batch changes. `{YourInterfaceName}Props`

**Comment by bretthayes** [comment]
@st0nebraker just following up to define how we can tackle this progressively going forward by creating new logic and updating logic as we come across it. Let's use the following style guide to help us:

- Keep all interfaces scoped at the top of our files defined directly under imports
- Use the same interface name as the component name and don't export it unless it's used in other files
- In the rare case that there is a namespace conflict with an exported interface being used as a type, we can use the `Props` suffix for the naming convention. (ie: `ButtonProps`)
- Use simplistic [descriptive names](https://google.github.io/styleguide/tsguide.html#descriptive-names) for components which will help define interface names

With the future blog work that will be done, this will potentially allow us to remove the common/global interfaces directory as I don't think we'll have a need for global interfaces. But if something comes up, we can just continue the conversation here in this issue to help improve and shape our style guide even more.

Some useful references that helped shape this style guide:
- [Google's naming conventions](https://google.github.io/styleguide/tsguide.html#naming-style)
- [Microsoft's TypeScript guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names)
- Naming conventions in [Mastering Interfaces in TypeScript](https://nicotsou.com/tltr-typescript-interfaces/)
- [This Stack Overflow thread](https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript/41967120#41967120)
