### ISSUE TITLE
Investigate GTM Snippet implementation

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5680]
Stakeholder: Lauren, Data & Analytics team
What: The ROIDNA analytics audit reported an improvement in how GTM is added to our templates.
Why: D&A and Marketing want to ensure the GA/GTM implementation is done and configured correctly

[Audit findings and action items](https://docs.google.com/spreadsheets/d/1RFlO5T0usDu6PK2SuQJG4X7CQ0z6H3C2isa-95fMXkY/edit#gid=1484601832) - row 26

![Image](https://user-images.githubusercontent.com/88658267/186126788-9f63048e-8b73-4035-bcba-10ffa26de875.png)

Requirements:
 - Go through the [recommended implementation of GTM](https://developers.google.com/tag-platform/tag-manager/web)
 - Investigate how we are currently adding the GTM snippet to our templates and determine if an update is required.
 - Is there a risk of any of the other scripts not working if an update is required?

**Comment by bretthayes** [comment]
For context, the noscript is rendering in the body which follows ROIDNAs recommendation, but we're loading the GTM script in the body as well since that's what [Next.js recommends](https://nextjs.org/docs/basic-features/script#afterinteractive). The example in their documentation uses the `afterInteractive` strategy which loads it in the body. Their docs state:

> Examples of scripts that are good candidates to load immediately after the page becomes interactive include:
> - Tag managers
> - Analytics

What's interesting is Google also recommends that the GTM script loads in the head, but the noscript loads in the body. This conflicts with the recommendation of Next.js. See screenshot below taken from GTM instructions. You can view this modal in the GTM dashboard by clicking on the tag id, top right.

![Screen Shot 2022-09-21 at 4 02 23 PM](https://user-images.githubusercontent.com/1733936/191599707-36403f55-e82e-464f-8f86-aa4164b9f7a1.png)

cc: @elzannewentzel @st0nebraker
