### ISSUE TITLE
Fix sitemap 404 errors

### ISSUE THREAD

**Issue by elzannewentzel** [sourcegraph/about#5712]
Stakeholders: Nick (DG), Fabiana, ROIDNA
What: Implement the XML Sitemap optimisations specified in the audit feedback.
Why: Several sitemaps submitted to GSC return a 404 status, and among the valid sitemaps, there is a relatively low proportion of valid URLs.

Assets: 
 - [Audit document](https://docs.google.com/spreadsheets/d/1bG5Zv03CPK4HpAqj6X6A9EGGuJmdTao5kLJUqoCQTTc/edit#gid=1712436774)

Requirements:
 - Fix the 404 errors for the sitemap.xml and sitemap-pages.xml files
 - Check what the empty sitemap file is for, and if not required, remove it
![Image](https://user-images.githubusercontent.com/88658267/188139316-c1dbbac5-e8fd-4b8a-9efc-f1d0f548fafd.png)
 - We are waiting for access to GSC, and once we have that, we can use it to upload new sitemaps and index faster.
 - The issue with the handbook will be covered in another task.

**Comment by bretthayes** [comment]
@elzannewentzel I think re-submitting a new `sitemap.xml` to the Google Search Console should fix the first 3 rows listed in that spreadsheet since row 2 and 3 probably won't ever exist again after we generate a new simpler `sitemap.xml` in #5711. This will also fix all the 404s and broken URLs that have been indexed in the past but no longer exist anymore on the about subdomain. Since we don't have a lot of URLs to index anymore on the about subdomain (now that the handbook is on another subdomain), one sitemap.xml generated from nextjs should do the trick.

**Comment by bretthayes** [comment]
I've submitted the newly generated [sitemap.xml](https://search.google.com/search-console/sitemaps/info-drilldown?resource_id=sc-domain:sourcegraph.com&sitemap=https:%2F%2Fabout.sourcegraph.com%2Fsitemap.xml) for About in GSC under the dot com property. I also submitted the [handbook sitemap](https://search.google.com/search-console/sitemaps/info-drilldown?resource_id=sc-domain:sourcegraph.com&sitemap=https:%2F%2Fhandbook.sourcegraph.com%2Fsitemap.xml) as well. So that should fix all 4 rows in the spreadsheet in the screenshot.
