### ISSUE TITLE
CTA 3 in dark mode pages isn't visible

### ISSUE THREAD

**Issue by omar2205** [sourcegraph/about#5977]
![image](https://user-images.githubusercontent.com/1373867/215360689-596f149c-8aa0-49a4-9ae5-d12561d4ce95.png)

![image](https://user-images.githubusercontent.com/1373867/215360724-063ee615-f3f0-46c7-a247-1c472e1ff81c.png)

https://about.sourcegraph.com/case-studies/cern-reduces-technical-debt

**Comment by sqs** [comment]
Thanks for reporting this. This appears to be a discrepancy between the dev version and the live version. I can repro the issue on the live version at https://about.sourcegraph.com/case-studies/cern-reduces-technical-debt, but on the dev version the problem is not present:

![image](https://user-images.githubusercontent.com/1976/215401555-5fa924ac-b4f4-431f-8f6f-f7de243eb6aa.png)

Because of that, I will submit a different PR to fix it. Thank you for submitting #5978, but I think the right fix is to the underlying issue that is causing dev and live to diverge.

**Comment by omar2205** [comment]
Alright, please go ahead and close that PR then!
