### ISSUE TITLE
Deprecate Eventlogger since we use GTM

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/about#606]
Since we switched to Google Tag Manager, Eventlogger is no longer functioning.  We should take advantage of GTM features to track all button clicks, as documented here:

http://www.clixmarketing.com/blog/2017/12/19/time-to-start-tracking-your-button-clicks-in-google-tag-manager/

**Comment by dadlerj** [comment]
The about site's event logging has been off for a while now, so I can say for sure this isn't in use currently.

That said, I always hated the "capture every click"-type trackers, since the reams of data you get back are so rarely connected to what you actually care about, and it becomes annoying to find the exact DOM selectors needed to figure out whether the click was on the button you cared about vs. another one that had the same classes. (I recall this from Heap in particular). 

That said, this hasn't actually been working/tracking at all for many months now, so this sort of concern with GTM and similar alternatives is purely theoretical 😄

**Comment by aileenrose** [comment]
@dadlerj  As I was digging through the code last night and reviewing the data on GA, it looks like there was good intention to track all interactions.   I think I will narrow the focus on just the CTAs which will be helpful in CRO work.   Also, heat maps from Crazyegg are probably all we need.

**Comment by dadlerj** [comment]
Awesome — to be clear, I'm not defending keeping eventlogger at all. It's unmaintained and entirely unused, I was just delivering some input here that I thought might be helpful to you and @ebrodymoore regarding why we had opted for in-house logging in the past.

**Comment by aileenrose** [comment]
Eventlogger dismantled in https://github.com/sourcegraph/about/pull/616
CLOSED
