### ISSUE TITLE
About site not loading/partially loading on Firefox

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6250]
URGENT. 
Issues identified on Firefox: 
- takes forever to load
- sometimes partially loads with missing content / no scripts
- when it does load the header intersects the nav bar

**Comment by fabicastp** [comment]
https://github.com/sourcegraph/about/assets/81499360/b95b4048-1ef5-48bb-be2a-b3dc7f86dbdf

**Comment by iskyOS** [comment]
These issues are specific to https://about.sourcegraph.com/ on the Firefox browser. It _looks_ like things are OK on Safari and Chrome.

There's also general weirdness with the site on Firefox when it does load. For example, random text is getting centered rather than left-aligned.
![CleanShot 2023-05-10 at 11 35 31](https://github.com/sourcegraph/about/assets/13739780/1455d45f-a9eb-4b18-b05b-cde44eabae76)
