### ISSUE TITLE
Issue w/ hidden fields and forms enrichment

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/about#6448]
**Context**
Our website is coded only to show the work email and the Policy Agreement checkbox. Then populate with other fields (name, company, etc.) if the email is unknown. 

We recently encountered an error with a submission. The user's is filling in the email field with her work email, but the rest of the fields are not populating because she's cookied in Hubspot with a profile that does not have a name and job. These two are required fields, so Hubspot is not accepting the submission. 

Questions need answers to: 
- What custom code hides the form fields? Where does it live? 
- Where is the forms enrichment coming from? Who is giving us that information? 
- What are the risks and implications of removing the script? 

_____________

After we find answers to the questions above, we count on your expertise to propose next steps. Some solutions that come to mind: 

- Solution 1: Find and remove the custom javascript that is hiding the fields and enriching the forms
- Solution 2 (not recommended): Add a logic to force the form to auto-populate empty fields with a default value when there's an error in the submission. This involves adding more complexity to an already complex script, so not recommended, but may be proposed as a short-term solution. 

**Assumptions**
- The validation/hiding logic doesn't come from Hubspot
- Code isn't introduced via GTM 
- This is a custom javascript that someone added at some point

**Relevants PRs**

- [Fix HubSpot form loading #5291](https://github.com/sourcegraph/about/pull/5291)
- Master form to simplify the  rendering time where most of the logic is: [#5483 HubSpot Master Forms](https://github.com/sourcegraph/about/pull/5483) /// [Sourcegraph search](https://sourcegraph.com/github.com/sourcegraph/about/-/blob/src/components/HubSpotForm.tsx)

Most recently (March '23) 

- [[Bug fix] Force display false hidden fields #6123](https://github.com/sourcegraph/about/pull/6123/files)
- [Blog: HubSpot forms are disappearing #6140](https://github.com/sourcegraph/about/pull/6140)

**Comment by gitstart-sourcegraph** [comment]
### 1. What custom code hides the form fields? Where does it live?

It's from `ClearbitForHubspot`, when a user enters an email, there is a request for getting informations which are related to that email.

This is the script which we inject manually when loading form: https://hubspot.clearbit.com/v1/forms/pk_a66b9ed76e62c713c06aab39bfae7234/forms.js
![Screenshot 2023-08-11 at 21 16 36](https://github.com/sourcegraph/about/assets/89894075/9b04cb3f-a2f8-47bb-ab74-c87d0835de03)


Once the form is submitted, HubspotForm saved the filled form fields with the cookie `hubspotutk` and will restore the saved info when the form is loaded again.

![Screenshot 2023-08-11 at 21 17 18](https://github.com/sourcegraph/about/assets/89894075/619aff4f-879c-4063-99d6-8cfc778bb4b9)


### 2. Where is the forms enrichment coming from? Who is giving us that information?

Data is from `hubspot.clearbit.com`  but I'm not sure how they could have it. I tried some emails, one gives only **Company name**, another gives only **First and Last name** and the last one gives **Company name and Phone number (of company)**.

### 3. What are the risks and implications of removing the script?

I don't think there is any risk with it.

### Query Regarding this Issue.
Could you please provide details about the specific page and form where this issue was encountered?

### Proposed Solutions
1. Update the clearbit config to disable shortening form, so we can keep form enrich. Details [here](https://clearbit.com/resources/guides/HubSpot-improve-data-accuracy#1-enable-clearbit-form-shortening-for-hubspot).
2. **Solution 1**: Find and remove the custom javascript that is hiding the fields and enriching the forms.
